// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// -------- //
// neopixel //
// -------- //

#define neopixel_wrap_target 0
#define neopixel_wrap 3
#define neopixel_pio_version 1

static const uint16_t neopixel_program_instructions[] = {
            //     .wrap_target
    0x6421, //  0: out    x, 1            side 0 [4]
    0x1223, //  1: jmp    !x, 3           side 1 [2]
    0x1300, //  2: jmp    0               side 1 [3]
    0xa342, //  3: nop                    side 0 [3]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program neopixel_program = {
    .instructions = neopixel_program_instructions,
    .length = 4,
    .origin = -1,
    .pio_version = neopixel_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config neopixel_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + neopixel_wrap_target, offset + neopixel_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}
#endif

// ----------------- //
// neopixel_parallel //
// ----------------- //

#define neopixel_parallel_wrap_target 0
#define neopixel_parallel_wrap 3
#define neopixel_parallel_pio_version 1

static const uint16_t neopixel_parallel_program_instructions[] = {
            //     .wrap_target
    0x6028, //  0: out    x, 8
    0xa20b, //  1: mov    pins, ~null            [2]
    0xa301, //  2: mov    pins, x                [3]
    0xa303, //  3: mov    pins, null             [3]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program neopixel_parallel_program = {
    .instructions = neopixel_parallel_program_instructions,
    .length = 4,
    .origin = -1,
    .pio_version = neopixel_parallel_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config neopixel_parallel_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + neopixel_parallel_wrap_target, offset + neopixel_parallel_wrap);
    return c;
}
#endif

